logging:
  level:
    root: info
    com.czetsuyatech: debug

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/nerv-examples?currentSchema=nervaudit
    driver-class-name: org.postgresql.Driver
    username: nerv
    password: nerv
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 17
      minimum-idle: 10
      pool-name: ct-pool
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: nervaudit
        envers:
          autoRegisterListeners: false
    generate-ddl: false
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.${nerv.audit.audit-strategy-type}-changelog-master.xml
    default-schema: nervaudit
    fail-on-error: true

nerv:
  audit:
    audit-insert: true
    audit-strategy-type: vertical
