spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nerv-example}
    driver-class-name: org.postgresql.Driver
    username: nerv
    password: nerv
    hikari:
      connection-test-query: SELECT 1
      jdbc-url: ${spring.datasource.url}
      maximum-pool-size: 17
      minimum-idle: 10
      pool-name: ct-pool-example
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      org.hibernate.envers.audit_strategy: org.hibernate.envers.strategy.ValidityAuditStrategy
  liquibase:
    change-log: db/changelog/db.changelog-master.xml

nerv:
  audit:
    audit-insert: true
    audit-strategy-type: vertical
