debug: true

server:
  port: 8080

management:
  tracing:
    export:
      enabled: true
    sampling:
      probability: 1.0

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      group-id: nerv-exception-demo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "com.czetsuyatech.nerv.example.exception.kafka,com.czetsuyatech.nerv.exception.event"

resilience4j:
  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 2000ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - feign.RetryableException

nerv:
  exception:
    enabled: true
    web:
      enabled: true
    feign:
      enabled: true
    event:
      enabled: true
    kafka:
      enabled: true
      source: nerv-exception-demo
      dlq-topic-suffix: .dlq
